import test from 'node:test';import assert from 'node:assert/strict';
import {emptyTeam} from '../src/lib/seed.ts';import {newChangeDraft,saveChangeTask,saveChangeSchema,loadBaseline} from '../src/lib/change-intake.ts';import {changeTypes,changeFields,type ChangeBaseline} from '../src/lib/change-form.ts';import {validateExtraction,extractChange} from '../src/lib/change-extraction.ts';import {chatFileText} from '../src/lib/chat-text.ts';import {applyAction} from '../src/lib/domain.ts';
function fixture(){const team=emptyTeam('Test');team.members.push({id:'alice',name:'Alice',login:'alice',password:'',active:true,role:'admin'});const actor={teamId:team.id,memberId:'alice'};const baseline:ChangeBaseline={client:{id:'client',code:'C01',display_name:'Test Client',revision:1,addresses:[{line1:'Old Street'}]},policy:{id:'term',key:'term:term',revision:1,currentSubjects:[{kind:'vehicle',id:'car',name:'Old car'}]},assets:[],selectedRisk:{kind:'vehicle',id:'car',name:'Old car'},selection:{clientId:'client',policyKey:'term:term',assetId:'',riskIndex:0,addressIndex:0},oldValues:{line1:'Old Street'}};return {team,actor,baseline};}
const proposed={effectiveDate:'2026-10-01',scope:'mailing',line1:'New Street',reason:'Moving'};
function input(id:string){return {draftId:id,proposed,sourceIds:[],evidence:{},extraction:'manual',ownerId:null,priority:'normal',reviewed:true};}
test('server snapshot remains immutable and retained on a task without changing ClientCore data',()=>{const {team,actor,baseline}=fixture();const before=structuredClone(baseline);const draft=newChangeDraft(team,actor,'address',baseline);const result=saveChangeTask(team,actor,input(draft.id),baseline);assert.equal(team.tasks[0].changeForm?.baseline.oldValues.line1,'Old Street');assert.equal(team.tasks[0].changeForm?.proposed.line1,'New Street');assert.deepEqual(baseline,before);assert.equal(team.tasks[0].customerRef?.clientCoreId,'client');assert.equal(saveChangeTask(team,actor,input(draft.id),baseline).taskId,result.taskId);assert.equal(team.tasks.length,1);assert.throws(()=>saveChangeTask(team,actor,{...input(draft.id),proposed:{...proposed,line1:'Other'}},baseline),/已经建立/);});
test('tampered baseline fields and stale data cannot be saved',()=>{const {team,actor,baseline}=fixture();const d=newChangeDraft(team,actor,'address',baseline);assert.throws(()=>saveChangeSchema.parse({...input(d.id),baseline:{}}));assert.throws(()=>saveChangeTask(team,actor,input(d.id),{...baseline,client:{...baseline.client,revision:2}}),/旧信息已变化/);assert.equal(team.tasks.length,0);});
test('foreign source, foreign draft, missing review and impossible date are rejected',()=>{const {team,actor,baseline}=fixture();const d=newChangeDraft(team,actor,'address',baseline);team.sources.push({id:'foreign',sender:'bob',messageId:'x',receivedAt:'',entries:[],state:'ready',taskIds:[]});assert.throws(()=>saveChangeTask(team,actor,{...input(d.id),sourceIds:['foreign']},baseline));assert.throws(()=>saveChangeTask(team,actor,{...input(d.id),reviewed:false},baseline));assert.throws(()=>saveChangeTask(team,actor,{...input(d.id),proposed:{...proposed,effectiveDate:'2026-02-30'}},baseline));assert.throws(()=>saveChangeTask(team,{...actor,memberId:'bob'},input(d.id),baseline));});
test('all supported change types create their matching workflow and preserve specific requests',()=>{for(const type of changeTypes){const {team,actor,baseline}=fixture();if(type.startsWith('property'))baseline.selectedRisk={kind:'property',name:'Old House'};const d=newChangeDraft(team,actor,type,baseline);const values=Object.fromEntries(changeFields[type].filter(f=>f.required).map(f=>[f.key,f.kind==='date'?'2026-10-01':f.options?Object.keys(f.options)[0]:f.key==='year'?'2026':'Test '+f.key]));saveChangeTask(team,actor,{...input(d.id),proposed:values},baseline);assert.equal(team.tasks[0].type,type);assert.deepEqual(team.tasks[0].changeForm?.proposed,values);assert.ok(team.tasks[0].workflow?.steps.length);}});
test('removal/replacement requires a specific old object; wrong asset kind rejected',()=>{for(const type of ['vehicle_remove','vehicle_replace','property_remove'] as const){const {team,actor,baseline}=fixture();baseline.selectedRisk=null;const d=newChangeDraft(team,actor,type,baseline);const values=Object.fromEntries(changeFields[type].filter(f=>f.required).map(f=>[f.key,f.kind==='date'?'2026-10-01':f.options?Object.keys(f.options)[0]:f.key==='year'?'2026':'x']));assert.throws(()=>saveChangeTask(team,actor,{...input(d.id),proposed:values},baseline),/旧车辆或房产/);}});
test('chat extraction only accepts supported fields with exact source evidence and valid dates',()=>{const text='新地址：20 Test Street，2026-10-01搬家';const r=validateExtraction('address',text,{fields:[{key:'line1',value:'20 Test Street',evidence:'新地址：20 Test Street'}],warnings:[]});assert.equal(r.values.line1,'20 Test Street');assert.throws(()=>validateExtraction('address',text,{fields:[{key:'line1',value:'x',evidence:'invented'}],warnings:[]}));assert.throws(()=>validateExtraction('address',text,{fields:[{key:'clientId',value:'x',evidence:'新地址'}],warnings:[]}));assert.throws(()=>validateExtraction('address',text,{fields:[{key:'effectiveDate',value:'2026-02-30',evidence:'新地址'}],warnings:[]}));});
test('model receives schema and untrusted chat only, with no client database snapshot or tool access',async()=>{const original=globalThis.fetch,env={...process.env};process.env.AI_BASE_URL='https://example.test';process.env.AI_MODEL='test-model';process.env.AI_API_KEY='test-key';let sent:any;globalThis.fetch=async(url,init)=>{if(String(url).endsWith('/models'))return Response.json({data:[{id:'test-model'}]});sent=JSON.parse(String(init?.body));return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify({fields:[{key:'line1',value:'20 Test Street',evidence:'20 Test Street'}],warnings:[]})}}]});};try{const result=await extractChange('address','新地址 20 Test Street');assert.equal(result.values.line1,'20 Test Street');assert.match(sent.messages[0].content,/不可信/);assert.equal(sent.messages[1].content,'新地址 20 Test Street');assert.equal(sent.tools,undefined);}finally{globalThis.fetch=original;for(const k of ['AI_BASE_URL','AI_MODEL','AI_API_KEY'])if(env[k]===undefined)delete process.env[k];else process.env[k]=env[k];}});
test('UTF8 chat uploads preserve evidence and reject binary or oversized text',async()=>{assert.equal((await chatFileText(Buffer.from('新地址：20 Test Street'),'chat.txt')).text,'新地址：20 Test Street');await assert.rejects(chatFileText(Buffer.from([0xff,0xfe]),'chat.txt'));await assert.rejects(chatFileText(Buffer.from('a\0b'),'chat.txt'));await assert.rejects(chatFileText(Buffer.from('x'.repeat(60001)),'chat.txt'));});
test('saved change forms cannot be reassigned to another customer/type through ordinary task edits',()=>{const {team,actor,baseline}=fixture();const d=newChangeDraft(team,actor,'address',baseline);saveChangeTask(team,actor,input(d.id),baseline);const t=team.tasks[0];const {title,type,priority,insuranceLine,customer,customerRef,description,ownerId,dueDate,status,waitingReason,checklist}=t;assert.throws(()=>applyAction(team,actor,{op:'updateTask',taskId:t.id,version:t.version,patch:{title,type:'vehicle_add',priority,insuranceLine,customer,customerRef,description,ownerId,dueDate,status,waitingReason,checklist}}),/锁定客户/);});
