import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {intakeQuote,verifyIntakeSignature} from '../src/lib/quote-intake.ts';
import {emptyTeam} from '../src/lib/seed.ts';
function fixture(){const team=emptyTeam('Intake');team.demo=false;team.members.push({id:'owner',name:'Owner',login:'owner',password:'',role:'admin',active:true});return {team,actor:{teamId:team.id,memberId:'owner'}};}
const input={id:'submission-test-1',receivedAt:'2026-09-28T12:00:00Z',payload:{quoteType:'both',locale:'en',submittedAt:'2026-09-28T11:59:00Z',fields:{full_name:'Fictional Quote',email:'quote@example.test',auto_eff_date:'2026-10-10',home_eff_date:'2026-10-01',licence_num:'TEST ONLY',unknown_future:'preserved'}}};
test('form creates one unassigned quote task, retains both dates and all source facts without linking a client',()=>{const {team,actor}=fixture();const r=intakeQuote(team,actor,input);assert.equal(team.tasks.length,1);const task=team.tasks[0];assert.equal(r.taskId,task.id);assert.equal(task.type,'lead');assert.equal(task.insuranceLine,'combined');assert.equal(task.customerRef,null);assert.equal(task.ownerId,null);assert.equal(task.dueDate,'2026-10-01');assert.ok(task.workflow?.steps.every(s=>s.state==='pending'));assert.deepEqual(team.sources[0].quoteSubmission?.payload.fields,input.payload.fields);assert.ok(!task.description.includes('TEST ONLY'));});
test('same submission replays idempotently; changed payload cannot silently overwrite',()=>{const {team,actor}=fixture();const first=intakeQuote(team,actor,input);assert.deepEqual(intakeQuote(team,actor,{...input,receivedAt:'2026-09-28T13:00:00Z'}),{...first,duplicate:true});assert.equal(team.tasks.length,1);assert.throws(()=>intakeQuote(team,actor,{...input,payload:{...input.payload,fields:{...input.payload.fields,full_name:'Different'}}}),/不一致/);assert.equal(team.sources.length,1);});
test('invalid or irrelevant effective dates do not create misleading deadlines',()=>{const {team,actor}=fixture();intakeQuote(team,actor,{...input,payload:{...input.payload,quoteType:'home',fields:{...input.payload.fields,home_eff_date:'2026-02-30'}}});assert.equal(team.tasks[0].dueDate,null);assert.equal(team.tasks[0].insuranceLine,'home');});
test('malformed, oversized, demo and unauthorized submissions cannot create tasks',()=>{const {team,actor}=fixture();assert.throws(()=>intakeQuote(team,actor,{...input,payload:{...input.payload,fields:{full_name:'Name'}}}));assert.throws(()=>intakeQuote(team,actor,{...input,payload:{...input.payload,fields:{...input.payload.fields,...Object.fromEntries(Array.from({length:20},(_,i)=>['field_'+i,'x'.repeat(1900)]))}}}));assert.throws(()=>intakeQuote(team,{...actor,memberId:'missing'},input));team.demo=true;assert.throws(()=>intakeQuote(team,actor,input));assert.equal(team.tasks.length,0);});
test('signature binds body, path and timestamp and rejects stale, missing or invalid signatures',()=>{const secret='s'.repeat(32),at=Date.now(),timestamp=String(at),raw=JSON.stringify(input);const signature=createHmac('sha256',secret).update(timestamp+'\nPOST\n/api/integrations/cantrust\n'+raw).digest('hex');assert.ok(verifyIntakeSignature(raw,timestamp,signature,secret,at));assert.ok(!verifyIntakeSignature(raw+' ',timestamp,signature,secret,at));assert.ok(!verifyIntakeSignature(raw,timestamp,signature,secret,at+300001));assert.ok(!verifyIntakeSignature(raw,timestamp,signature,undefined,at));assert.ok(!verifyIntakeSignature(raw,timestamp,'bad',secret,at));});

test('JSONB object key reordering preserves replay identity',()=>{const {team,actor}=fixture();intakeQuote(team,actor,input);const source=team.sources[0];const payload=source.quoteSubmission!.payload;source.quoteSubmission!.payload=Object.fromEntries(Object.entries(payload).reverse()) as typeof payload;assert.equal(intakeQuote(team,actor,input).duplicate,true);});
