'use client';
import {useState} from 'react';
import {changeFields,changeTypes,type ChangeType,type ChangeDraft,type ChangeForm} from '../lib/change-form';
import {taskTypeLabels} from '../lib/task-templates';
import type {Source} from '../lib/model';
import styles from './change-task-form.module.css';
async function api(path:string,body?:unknown){const r=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error||'请求失败');return data;}
function valueText(value:any):string{if(value===null||value===undefined||value==='')return '未记录';if(typeof value!=='object')return String(value);if(Array.isArray(value))return value.map(valueText).join('；');return Object.entries(value).filter(([k])=>!['id','revision','client_id','policy_id','created_at','updated_at'].includes(k)).map(([k,v])=>`${k}: ${valueText(v)}`).join(' · ');}
export function SavedChangeForm({form}:{form:ChangeForm}){return <details className={styles.saved} open><summary>变更申请表 · 旧信息已锁定</summary><p>读取时间：{new Date(form.capturedAt).toLocaleString('zh-CN')} · 申请内容尚未写入 ClientCoreBMS</p><div className={styles.comparison}><strong>变更项目</strong><strong>数据库旧信息</strong><strong>拟变更内容</strong>{changeFields[form.type].map(f=><div className={styles.row} key={f.key}><span>{f.label}</span><span>{form.baseline.oldValues[f.key]||'未记录／不适用'}</span><span>{f.options?.[form.proposed[f.key]]??form.proposed[f.key]??'—'}{form.evidence[f.key]&&<small>识别依据：{form.evidence[f.key]}</small>}</span></div>)}</div><details><summary>查看完整旧记录</summary><p>客户：{form.baseline.client.display_name} · {form.baseline.client.code}</p><p>原地址：{valueText(form.baseline.client.addresses)}</p><p>保单：{valueText(form.baseline.policy?{number:form.baseline.policy.policy_number??form.baseline.policy.policyNumber,insurer:form.baseline.policy.insurer,status:form.baseline.policy.status}:null)}</p><p>原承保对象：{valueText(form.baseline.policy?.currentSubjects??form.baseline.policy?.subjects)}</p><p>所选资产：{valueText(form.baseline.selectedRisk)}</p></details></details>;}
export default function ChangeTaskForm({sources,members,onCreated,initialType='address'}:{sources:Source[];members:{id:string;name:string;active:boolean}[];onCreated:(id:string)=>Promise<void>;initialType?:ChangeType}){
 const [type,setType]=useState<ChangeType>(initialType),[q,setQ]=useState(''),[candidates,setCandidates]=useState<any[]>([]),[ctx,setCtx]=useState<any>(null),[draft,setDraft]=useState<ChangeDraft|null>(null),[policyKey,setPolicyKey]=useState(''),[assetId,setAssetId]=useState(''),[riskIndex,setRiskIndex]=useState<number|null>(null),[addressIndex,setAddressIndex]=useState<number|null>(null);
 const [proposed,setProposed]=useState<Record<string,string>>({}),[evidence,setEvidence]=useState<Record<string,string>>({}),[sourceIds,setSourceIds]=useState<string[]>([]),[extraSources,setExtraSources]=useState<{id:string;name:string;text:string}[]>([]),[chat,setChat]=useState(''),[reviewed,setReviewed]=useState(false),[ownerId,setOwnerId]=useState(''),[priority,setPriority]=useState('normal'),[method,setMethod]=useState('manual'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 function invalidate(){setDraft(null);setReviewed(false);setEvidence({});}
 async function choose(c:any){await run(async()=>{const result=await api('/api/change-tasks?clientId='+encodeURIComponent(c.id));setCtx(result);setCandidates([]);setPolicyKey('');setAssetId('');setRiskIndex(null);setAddressIndex(result.client.addresses?.length===1?0:null);invalidate();setProposed({});setSourceIds([]);setExtraSources([]);setChat('');setNotice('');});}
 async function lock(risk:number|null=riskIndex){await run(async()=>{const result=await api('/api/change-tasks',{op:'snapshot',type,confirmedClient:true,selection:{clientId:ctx.client.id,policyKey,assetId,riskIndex:risk,addressIndex}});setDraft(result);setReviewed(false);});}
 async function upload(files:File[]){await run(async()=>{for(const file of files){const r=await fetch('/api/change-tasks/evidence',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});const result=await r.json();if(!r.ok)throw Error(result.error);setExtraSources(v=>[...v,{id:result.sourceId,name:file.name,text:result.text}]);setSourceIds(v=>[...v,result.sourceId]);if(result.warning)setNotice(result.warning);}setReviewed(false);});}
 async function identify(){await run(async()=>{let ids=[...sourceIds];if(chat.trim()){const source=await api('/api/change-tasks/evidence',{text:chat});ids.push(source.sourceId);setSourceIds(ids);setExtraSources(v=>[...v,{id:source.sourceId,name:'粘贴聊天记录',text:source.text}]);setChat('');}if(!ids.length)throw Error('请上传、选择或粘贴聊天记录');const result=await api('/api/change-tasks/extract',{draftId:draft!.id,sourceIds:ids});setProposed(previous=>{const next={...previous};for(const [key,value]of Object.entries(result.values))if(!next[key])next[key]=String(value);return next;});setEvidence(previous=>{const next={...previous};for(const [key,value]of Object.entries(result.evidence))if(!proposed[key])next[key]=String(value);return next;});setMethod(result.model);setReviewed(false);setNotice(['识别结果仅填入空白项，请逐项核对；已有填写未覆盖。',...result.warnings].join(' '));});}
 async function save(){await run(async()=>{let ids=[...sourceIds];if(chat.trim()){const source=await api('/api/change-tasks/evidence',{text:chat});ids.push(source.sourceId);setSourceIds(ids);setChat('');}const result=await api('/api/change-tasks',{op:'save',data:{draftId:draft!.id,proposed,sourceIds:ids,evidence,extraction:method,ownerId:ownerId||null,priority,reviewed:true}});await onCreated(result.taskId);});}
 return <div className={styles.form}>{error&&<p role="alert" className={styles.error}>{error}</p>}<p>确认客户 → 读取旧信息 → 识别新内容 → 核对并创建任务</p><label>变更类型<select disabled={busy} value={type} onChange={e=>{setType(e.target.value as ChangeType);invalidate();setProposed({});}}>{changeTypes.map(t=><option key={t} value={t}>{taskTypeLabels[t]}</option>)}</select></label>
 <section><h3>1. 查找并确认客户</h3><div className={styles.inline}><input aria-label="查找 ClientCoreBMS 客户" placeholder="客户编号、姓名或保单号" value={q} onChange={e=>setQ(e.target.value)}/><button type="button" disabled={busy||q.trim().length<2} onClick={()=>run(async()=>{const r=await api('/api/customers?q='+encodeURIComponent(q.trim()));setCandidates(r.items);if(!r.items.length)setNotice('未找到客户，请核对客户编号或姓名');})}>查找</button></div>{candidates.map(c=><button type="button" className={styles.candidate} disabled={busy} key={c.id} onClick={()=>choose(c)}>确认客户：{c.displayName} · {c.clientCode}</button>)}{ctx&&<><p><strong>已确认：{ctx.client.display_name} · {ctx.client.code}</strong></p><label>对应保单年度<select disabled={busy} value={policyKey} onChange={e=>{setPolicyKey(e.target.value);setRiskIndex(null);invalidate();}}><option value="">仅通讯地址可不选保单</option>{ctx.policies.map((p:any)=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label>{ctx.client.addresses?.length>1&&<label>旧通讯地址<select value={addressIndex??''} onChange={e=>{setAddressIndex(e.target.value===''?null:Number(e.target.value));invalidate();}}><option value="">选择对应地址</option>{ctx.client.addresses.map((a:any,i:number)=><option key={i} value={i}>{valueText(a)}</option>)}</select></label>}{ctx.assets.length>0&&<label>涉及的旧资产<select disabled={busy} value={assetId} onChange={e=>{setAssetId(e.target.value);setRiskIndex(null);invalidate();}}><option value="">不选择资产／按保单承保对象选择</option>{ctx.assets.filter((a:any)=>a.status==='active').map((a:any)=><option key={a.id} value={a.id}>{a.details.name} · {a.kind}</option>)}</select></label>}<button type="button" disabled={busy} onClick={()=>lock()}>读取并锁定旧信息</button></>}</section>
 {draft&&<><section><h3>2. 上传聊天记录</h3><p>支持 TXT、文字 PDF 和截图。原文件保留；无法识别的内容请手动补充。</p><input type="file" aria-label="上传变更聊天记录" accept=".txt,.pdf,image/png,image/jpeg,image/webp,image/gif" multiple disabled={busy} onChange={e=>{const files=Array.from(e.target.files??[]);e.target.value='';void upload(files);}}/><textarea aria-label="聊天原文" placeholder="或粘贴客户聊天原文" value={chat} onChange={e=>{setChat(e.target.value);setReviewed(false);}} rows={4}/><details><summary>从已有资料中选择</summary>{sources.filter(s=>s.state==='ready').map(s=><label key={s.id}><input type="checkbox" checked={sourceIds.includes(s.id)} onChange={e=>{setSourceIds(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id));setReviewed(false);setEvidence({});}}/>{s.uploadName||s.entries.find(e=>e.kind==='text')?.text.slice(0,80)||'聊天附件'}</label>)}</details>{extraSources.map(s=><details key={s.id}><summary>{s.name} · 已保留</summary><pre>{s.text||'没有提取到文字，请对照原文件手工填写。'}</pre></details>)}<button type="button" disabled={busy||(!chat.trim()&&!sourceIds.length)} onClick={identify}>{busy?'处理中…':'识别并填写新内容'}</button>{notice&&<p role="status">{notice}</p>}</section>
 <section><h3>3. 旧信息与拟变更内容</h3><p>旧信息来自 ClientCoreBMS，无法编辑 · {new Date(draft.capturedAt).toLocaleString('zh-CN')}</p>{!assetId&&(draft.baseline.policy?.currentSubjects??draft.baseline.policy?.subjects)?.length>0&&<label>本次涉及的旧承保对象<select disabled={busy} value={riskIndex??''} onChange={e=>{const index=e.target.value===''?null:Number(e.target.value);setRiskIndex(index);void lock(index);}}><option value="">请选择（移除／替换必选）</option>{(draft.baseline.policy.currentSubjects??draft.baseline.policy.subjects).map((s:any,i:number)=><option key={i} value={i}>{s.name||s.label||s.kind||'对象'} {i+1}</option>)}</select></label>}
 <div className={styles.oldContext}><label>原通讯地址<textarea readOnly value={valueText(draft.baseline.client.addresses)}/></label><label>原保单及承保对象<textarea readOnly rows={3} value={valueText(draft.baseline.policy?{policy:draft.baseline.policy.policy_number??draft.baseline.policy.policyNumber,insurer:draft.baseline.policy.insurer,status:draft.baseline.policy.status,subjects:draft.baseline.policy.currentSubjects??draft.baseline.policy.subjects}:null)}/></label><label>所选旧资产／对象<textarea readOnly rows={2} value={valueText(draft.baseline.selectedRisk)}/></label></div><div className={styles.comparison}><strong>变更项目</strong><strong>数据库旧信息 🔒</strong><strong>拟变更内容</strong>{changeFields[type].map(f=><div className={styles.row} key={f.key}><label htmlFor={'new-'+f.key}>{f.label}{f.required?' *':''}</label><textarea aria-label={'旧信息 '+f.label} readOnly value={draft.baseline.oldValues[f.key]||'未记录／不适用'} rows={2}/><div>{f.kind==='select'?<select id={'new-'+f.key} value={proposed[f.key]??''} onChange={e=>{setProposed(v=>({...v,[f.key]:e.target.value}));setEvidence(v=>{const n={...v};delete n[f.key];return n;});setReviewed(false);}}><option value="">待确认</option>{Object.entries(f.options!).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>:f.kind==='long'?<textarea id={'new-'+f.key} value={proposed[f.key]??''} rows={3} onChange={e=>{setProposed(v=>({...v,[f.key]:e.target.value}));setEvidence(v=>{const n={...v};delete n[f.key];return n;});setReviewed(false);}}/>:<input id={'new-'+f.key} type={f.kind==='date'?'date':'text'} value={proposed[f.key]??''} onChange={e=>{setProposed(v=>({...v,[f.key]:e.target.value}));setEvidence(v=>{const n={...v};delete n[f.key];return n;});setReviewed(false);}}/>}{evidence[f.key]&&<small>原文：{evidence[f.key]}</small>}</div></div>)}</div><details><summary>查看数据库原始地址、保单及资产</summary><pre>{JSON.stringify(draft.baseline,null,2)}</pre></details></section>
 <div className={styles.inline}><label>负责人<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">待分配</option>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>优先级<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="urgent">紧急</option><option value="high">高</option><option value="normal">普通</option><option value="low">低</option></select></label></div><label className={styles.confirm}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>我已核对客户、旧信息和拟变更内容。此操作仅创建办理任务。</label><button type="button" className="primary full" disabled={busy||!reviewed} onClick={save}>保存为新任务</button></>}
 </div>;
}
