'use client';
import {useEffect,useState,useRef} from 'react';
import WorkspaceShell from './workspace-shell';
import type {NavigationData} from './workspace-navigation';
import {visibleSteps} from '../lib/task-workflow';
import {paymentAmounts,type RenewalOffer} from '../lib/renewal-comparison';
import type {Task} from '../lib/model';
import styles from './renewal-review.module.css';

const money=(c:number|null|undefined)=>c==null?'待确认':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(c/100);
async function pdfBase64(file:File){if(file.size>25*1024*1024)throw Error('PDF 最大 25 MB');return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('文件读取失败'));reader.readAsDataURL(file);});}

function Snapshot({src,title,pages}:{src:string;title:string;pages?:number[]}) {
 const canvas=useRef<HTMLCanvasElement>(null),[page,setPage]=useState(0),[count,setCount]=useState(0),[zoom,setZoom]=useState(1),[error,setError]=useState('');
 useEffect(()=>{setPage(0);},[src]);
 useEffect(()=>{let stopped=false;let loading:any,render:any;setError('');
  void(async()=>{try{const pdf=await import('pdfjs-dist');if(stopped)return;pdf.GlobalWorkerOptions.workerSrc='/api/pdf-worker?v=6.3.289';loading=pdf.getDocument({url:src});const document=await loading.promise;if(stopped)return;setCount(pages?.length??document.numPages);const physical=pages?.[page]??page+1,p=await document.getPage(physical),viewport=p.getViewport({scale:1.25*zoom});const c=canvas.current;if(!c||stopped)return;c.width=Math.ceil(viewport.width);c.height=Math.ceil(viewport.height);render=p.render({canvasContext:c.getContext('2d')!,canvas:c,viewport});await render.promise;}catch(e){if(!stopped)setError(e instanceof Error?e.message:'快照读取失败');}})();
  return()=>{stopped=true;render?.cancel();void loading?.destroy();};
 },[src,page,zoom,JSON.stringify(pages)]);
 return <section className={styles.snapshot}><header><h3>{title}</h3><a href={src} target="_blank" rel="noreferrer">打开原件</a></header><div className={styles.pdfControls}><button disabled={page<=0} onClick={()=>setPage(p=>p-1)} aria-label={title+'上一页'}>上一页</button><span>{page+1} / {count||'…'} {pages?.[page]?`· 原件第 ${pages[page]} 页`:''}</span><button disabled={page+1>=count} onClick={()=>setPage(p=>p+1)} aria-label={title+'下一页'}>下一页</button><select aria-label={title+'缩放'} value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value="0.75">75%</option><option value="1">100%</option><option value="1.5">150%</option></select></div>{error?<p role="alert">{error}</p>:<div className={styles.canvasScroll}><canvas ref={canvas} aria-label={title}/></div>}</section>;
}

export default function RenewalReview({taskId}:{taskId?:string}) {
 const [navigation,setNavigation]=useState<NavigationData|null>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[frequency,setFrequency]=useState<'annual'|'monthly'>('annual');
 const [offers,setOffers]=useState<RenewalOffer[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[note,setNote]=useState(''),[price,setPrice]=useState(''),[policyNumber,setPolicyNumber]=useState(''),[effectiveDate,setEffectiveDate]=useState(''),[carrierConfirmed,setCarrierConfirmed]=useState(false),[pendingIssue,setPendingIssue]=useState(false),[documentKind,setDocumentKind]=useState('policy_original'),[fileTerm,setFileTerm]=useState('original'),[currentFile,setCurrentFile]=useState(''),[baselineChoice,setBaselineChoice]=useState(''),[annualBaseline,setAnnualBaseline]=useState(false),[billKind,setBillKind]=useState<'refund'|'charge'>('refund'),[dueDate,setDueDate]=useState(''),[ownerId,setOwnerId]=useState('');
 const dirty=useRef(false),task:Task|undefined=data?.task,flow=task?.workflow,r=task?.renewal,context=data?.context,original=context?.term,target=data?.target?.term,selected=offers.find(o=>o.id===selectedId);
 const baselineFilled=useRef<string|null>(null);
 const [baselinePrice,setBaselinePrice]=useState(''),[billingPrice,setBillingPrice]=useState(''),[cancelConfirmed,setCancelConfirmed]=useState(false),[billingConfirmed,setBillingConfirmed]=useState(false);
 useEffect(()=>{if(r?.kind!=='source'||original||baselineFilled.current===r.targetId)return;const value=context?.target?.annualPremiumCents??context?.target?.termPremiumCents;const shown=context?.target?.displayedPremium;if(value!=null||typeof shown==='string'&&/^\d+(\.\d{1,2})?$/.test(shown)){setBaselinePrice(value!=null?(value/100).toFixed(2):shown);setAnnualBaseline(context?.target?.annualPremiumCents!=null);}baselineFilled.current=r.targetId;},[r?.targetId,context,original]);
 const disabled=busy||!!r?.pending||!!data?.billing?.pending||!!task?.archived||navigation?.me.role!=='admin';
 async function load(){const res=await fetch('/api/renewals'+(taskId?'?taskId='+encodeURIComponent(taskId):''),{cache:'no-store'}),next=await res.json();if(!res.ok)throw Error(next.error);setData(next);if(next.task?.renewal&&!dirty.current){const saved=next.task.renewal.offers;const found=(next.jobs??[]).flatMap((j:any)=>(j.result?.offers??[]).map(({currency,...o}:any)=>({...o,id:j.id+':'+o.id,jobId:j.id})));setOffers([...saved,...found.filter((o:RenewalOffer)=>!saved.some((s:RenewalOffer)=>s.jobId===o.jobId))]);setSelectedId(next.task.renewal.selectedId??null);}}
 useEffect(()=>{void fetch('/api/state',{cache:'no-store'}).then(r=>r.json()).then(setNavigation);void load().catch(e=>setError(String(e)));},[taskId]);
 useEffect(()=>{if(!taskId)return;const timer=setInterval(()=>{void load().catch(()=>{});},10000);return()=>clearInterval(timer);},[taskId]);
 async function action(op:string,extra:any={}){if(!task)return;setBusy(true);setError('');try{const res=await fetch('/api/renewals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId,version:task.version,op,data:extra})}),b=await res.json();if(!res.ok)throw Error(b.error);if(['comparison','rebase'].includes(op))dirty.current=false;await load();}catch(e){setError(e instanceof Error?e.message:'操作未完成');await load().catch(()=>{});}finally{setBusy(false);}}
 async function start(kind:string,targetId:string,clientId:string){setBusy(true);setError('');try{const res=await fetch('/api/renewals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'start',data:{kind,targetId,clientId,taskId}})}),b=await res.json();if(!res.ok)throw Error(b.error);window.location.href='/insurance-review?taskId='+encodeURIComponent(b.taskId);}catch(e){setError(String(e));setBusy(false);}}
 async function upload(file:File,formal=false){setBusy(true);try{const base64=await pdfBase64(file);await action(formal?'file':'quote',{name:file.name,base64,key:crypto.randomUUID(),...(formal?{termId:fileTerm==='original'?original?.id:target?.id,documentKind}:{})});}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function manual(key:string,state='done'){if(!task)return;setBusy(true);try{const res=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'workflow.step',taskId,version:task.version,key,state,note})}),b=await res.json();if(!res.ok)throw Error(b.error);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'logout'})});window.location.href='/';}
 const displayed=context?.target?.displayedPremium,displayedCents=typeof displayed==='string'&&/^\d+(\.\d{1,2})?$/.test(displayed)?Math.round(Number(displayed)*100):null;
 const current=original?.currentPremium,currentCents=current?.premiumCents??original?.premium_cents??context?.target?.annualPremiumCents??context?.target?.termPremiumCents??displayedCents;
 const currentBasis=current?.basis??(context?.target?.annualPremiumCents!=null?'annual':'term'),line=task?.insuranceLine??'other',currentPay=paymentAmounts(currentCents,line,currentBasis),newPay=selected?.amountKind==='pre_tax'?paymentAmounts(selected.premiumCents,line,selected.basis):null;
 const display=(c:number|null,p:ReturnType<typeof paymentAmounts>)=>frequency==='annual'?(p?money(p.annual):money(c)):p?money(p.monthly):'需要年度税前保费';
 const files=(context?.files??[]).filter((f:any)=>['policy_original','renewal_original','endorsement'].includes(f.document_kind)),shownFile=files.find((f:any)=>f.id===currentFile)??files[0];
 const quoteCleaned=selected&&(data?.jobs??[]).find((j:any)=>j.id===selected.jobId)?.cleanedAt,newFile=(data?.target?.files??[]).find((f:any)=>['policy_original','renewal_original'].includes(f.document_kind));
 const pdfUrl=(key:string,id:string)=>'/api/renewals?taskId='+encodeURIComponent(taskId!)+'&'+key+'='+encodeURIComponent(id);
 return <WorkspaceShell page={taskId?'insurance':'renewals'} data={navigation} onLogout={logout} className={styles.page}><main>
  <header className={styles.heading}><div><small>RENEWAL WORKSPACE</small><h1>{task?.customer??'续保任务'}</h1><p>{taskId?'从目前保单快照到最终办理结果。':'未来 60 天与已逾期未处理保单。'}</p></div><a href="/?page=board">返回看板</a></header>
  {error&&<p className={styles.error} role="alert">{error}</p>}
  {!data&&<p>正在拉取资料…</p>}
  {!taskId&&data&&<div className={styles.queue}>{data.items?.map((x:any)=><article key={x.targetKind+':'+x.targetId}><div><small>{x.clientCode} · {x.expiryDate}</small><h2>{x.clientName}</h2><p>{x.insurer} · {x.policyNumber}</p></div><button disabled={busy||navigation?.me.role!=='admin'} onClick={()=>start(x.targetKind,x.targetId,x.clientId)}>打开／建立续保任务</button></article>)}{!data.items?.length&&<p>没有待处理到期保单。</p>}</div>}
  {data?.billing&&<section className={styles.card}><h2>取消账务跟进</h2><p>{data.billing.context.term.insurer} · {data.billing.context.term.policy_number} · 取消日期 {data.billing.event?.effectiveDate}</p><p>BMS 当前账务金额：{money(data.billing.event?.amount?.cents)}</p><a href={'/insurance-review?taskId='+encodeURIComponent(data.billing.originalTaskId)}>查看原续保任务</a>{data.billing.pending&&<p>原账务提交待核实。<button disabled={busy} onClick={()=>action('retryBilling')}>核实／重试原账务提交</button></p>}<fieldset disabled={disabled}><label>账务结果<select value={billKind} onChange={e=>setBillKind(e.target.value as 'refund'|'charge')}><option value="refund">退款</option><option value="charge">费用／补收</option></select></label><label>实际确认金额 CAD<input type="number" min="0" step="0.01" value={billingPrice} onChange={e=>setBillingPrice(e.target.value)}/></label><label>保险公司账务依据<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label><input type="checkbox" checked={carrierConfirmed} onChange={e=>setCarrierConfirmed(e.target.checked)}/>已核对保险公司实际账务结果</label><button disabled={!billingPrice||!note.trim()||!carrierConfirmed} onClick={()=>action('completeBilling',{kind:billKind,cents:Math.round(Number(billingPrice)*100),note,carrierConfirmed})}>保存到 BMS 并完成账务跟进</button></fieldset>{task?.status==='done'&&!task.archived&&<p>账务结果已保存，完成超过一周后自动归档。</p>}{task?.archived&&<p>账务结果已保存，跟进任务已归档。</p>}</section>}
  {task&&!r&&!data?.billing&&<section className={styles.card}><h2>选择本次原保单年度</h2><select aria-label="原保单年度" value={baselineChoice} onChange={e=>setBaselineChoice(e.target.value)}><option value="">选择</option>{data.targets?.policies?.flatMap((p:any)=>p.terms.map((t:any)=><option key={t.id} value={'term:'+t.id}>{p.insurer} · {t.policyNumber} · {t.effectiveDate} — {t.expiryDate}</option>))}{data.targets?.sourcePolicies?.filter((p:any)=>!p.workflowTermId).map((p:any)=><option key={p.sourceId} value={'source:'+p.sourceId}>{p.insurer} · {p.policyNumber} · {p.expiryDate}（来源记录）</option>)}</select><button disabled={!baselineChoice||busy} onClick={()=>{const [kind,...id]=baselineChoice.split(':');void start(kind,id.join(':'),task.customerRef!.clientCoreId);}}>绑定年度</button></section>}
  {r&&context&&<>
   <div className={styles.identity}><span>{context.client.code}</span><span>{original?.policy_number??context.target.policyNumber}</span><span>{original?.insurer??context.target.insurer}</span><span>{original?.effectiveDate??context.target.effectiveDate} — {original?.expiryDate??context.target.expiryDate}</span><span>{context.client.contacts?.map((c:any)=>c.value).join(' · ')}</span></div>
   <details className={styles.card}><summary>客户与保单资料（自动读取）</summary><p>客户成员：{context.client.people?.map((p:any)=>p.name).join(' · ')||'尚未确认'}</p><p>地址：{context.client.addresses?.map((a:any)=>[a.line1,a.line2,a.city,a.province,a.postalCode].filter(Boolean).join(', ')).join('；')||'尚未确认'}</p><p>本年度投保人：{(original?.currentApplicants??context.target.applicants)?.map((a:any)=>a.name).join(' · ')||'尚未确认'}</p><p>本年度标的：{(original?.currentSubjects??context.target.subjects)?.map((s:any)=>[s.name,s.description].filter(Boolean).join(' — ')).join('；')||'请查看原保单快照'}</p><p>客户资产档案：{context.assets?.filter((a:any)=>a.status==='active').map((a:any)=>a.details.name).join('；')||'尚未确认'}</p></details>
   {r.pending&&<div className={styles.notice}>上次提交结果待核实。<button disabled={busy} onClick={()=>action('retry')}>核实／重试原提交</button></div>}
   {!original&&<section className={styles.card}><h2>首次核对目前已签发保单</h2><p>已有来源资料自动带入；确认目前保单税前金额后建立正式年度，并在下方补传现有原件。</p><label>目前税前保费 CAD<input type="number" min="0" step="0.01" value={baselinePrice} onChange={e=>setBaselinePrice(e.target.value)}/></label><label>核对依据<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label><input type="checkbox" checked={annualBaseline} onChange={e=>setAnnualBaseline(e.target.checked)}/>确认这是完整年度税前保费</label><button disabled={disabled||!baselinePrice||!note.trim()} onClick={()=>action('adopt',{premiumCents:Math.round(Number(baselinePrice)*100),basis:annualBaseline?'annual':'term',note,confirmed:true})}>确认并建立原年度</button></section>}
   {context.successorTermId&&flow?.decision==='stay'&&!target&&<div className={styles.notice}>BMS 已经创建续保年度。<button disabled={disabled} onClick={()=>action('attachRenewal')}>关联现有续保年度并继续归档</button></div>}
   {original&&r.baselineHash!==context.baselineHash&&!target&&!flow?.receipts.some(x=>x.stepKey==='cancel')&&<div className={styles.notice}>目前年度或快照已更新，确认客户决定前请重新核对。<button disabled={disabled} onClick={()=>action('rebase')}>核对后更新比较基线</button></div>}
   <section className={styles.prices}><header><h2>价格对照</h2><div role="group" aria-label="付款方式"><button aria-pressed={frequency==='annual'} onClick={()=>setFrequency('annual')}>年付</button><button aria-pressed={frequency==='monthly'} onClick={()=>setFrequency('monthly')}>月付</button></div></header><div className={styles.priceColumns}><article><small>目前保险</small><strong>{display(currentCents,currentPay)}</strong><p>{original?.insurer??context.target.insurer}</p>{currentPay&&frequency==='monthly'&&<small>尾期 {money(currentPay.lastMonth)} · 全年 {money(currentPay.monthlyTotal)}</small>}</article><article><small>选中方案</small><strong>{selected?display(selected.premiumCents,newPay):'上传报价后选择'}</strong><p>{selected?.insurer??'新方案'}</p>{newPay&&frequency==='monthly'&&<small>尾期 {money(newPay.lastMonth)} · 全年 {money(newPay.monthlyTotal)}</small>}</article><article><small>金额差额</small><strong>{currentPay&&newPay?money(frequency==='annual'?newPay.annual-currentPay.annual:newPay.monthly-currentPay.monthly):'待确认'}</strong><p>新方案减目前方案</p></article></div><small>月付为 12 期估算，零首付；车险年度手续费 1.3%，房险税 8%、年度手续费 3%。保险公司实际付款安排以确认文件为准。</small></section>
   <section className={styles.card}><div className={styles.row}><h2>报价方案</h2><label className={styles.upload}>上传 quote 一次<input aria-label="上传报价 PDF" type="file" accept="application/pdf" disabled={disabled||flow?.decision!=='undecided'} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file);}}/></label></div>
    {(data.jobs??[]).map((j:any)=><p key={j.id}>{j.cleanedAt?'临时报价已删除':j.state==='processing'?'正在识别价格及页面':j.state==='queued'?'等待识别':j.state==='auto_checked'?'识别完成':j.state} {j.message}{['failed','partial','waiting_configuration'].includes(j.state)&&!j.cleanedAt&&<button disabled={disabled} onClick={()=>action('retryQuote',{jobId:j.id,revision:j.revision})}>重试识别</button>}{!j.cleanedAt&&j.result?.pageCount&&!offers.some(o=>o.jobId===j.id)&&<button disabled={disabled} onClick={()=>{dirty.current=true;setOffers(o=>[...o,{id:j.id+':manual',jobId:j.id,insurer:'',premiumCents:null,effectiveDate:null,expiryDate:null,basis:'unknown',amountKind:'unknown',pages:Array.from({length:j.result.pageCount},(_,i)=>i+1)}]);}}>按原件补齐此报价</button>}</p>)}
    {offers.map((offer,i)=><fieldset key={offer.id} className={styles.offer} disabled={disabled}><label><input type="radio" name="selectedQuote" checked={selectedId===offer.id} onChange={()=>{dirty.current=true;setSelectedId(offer.id);}}/>方案 {i+1}</label><label>保险公司<input value={offer.insurer} onChange={e=>{dirty.current=true;setOffers(list=>list.map(o=>o.id===offer.id?{...o,insurer:e.target.value}:o));}}/></label><label>税前保费 CAD<input type="number" min="0" step="0.01" value={offer.premiumCents==null?'':(offer.premiumCents/100).toFixed(2)} onChange={e=>{dirty.current=true;setOffers(list=>list.map(o=>o.id===offer.id?{...o,premiumCents:e.target.value===''?null:Math.round(Number(e.target.value)*100)}:o));}}/></label><label>生效日<input type="date" value={offer.effectiveDate??''} onChange={e=>{dirty.current=true;setOffers(list=>list.map(o=>o.id===offer.id?{...o,effectiveDate:e.target.value||null}:o));}}/></label><label>到期日<input type="date" value={offer.expiryDate??''} onChange={e=>{dirty.current=true;setOffers(list=>list.map(o=>o.id===offer.id?{...o,expiryDate:e.target.value||null}:o));}}/></label><label>金额口径<select value={offer.basis+':'+offer.amountKind} onChange={e=>{dirty.current=true;const [basis,amountKind]=e.target.value.split(':');setOffers(list=>list.map(o=>o.id===offer.id?{...o,basis:basis as RenewalOffer['basis'],amountKind:amountKind as RenewalOffer['amountKind']}:o));}}><option value="unknown:unknown">待确认</option><option value="annual:pre_tax">年度税前</option><option value="term:pre_tax">整期税前</option><option value="annual:total">年度含税总额</option><option value="term:total">整期含税总额</option></select></label><label>快照页码<input value={offer.pages.join(',')} onChange={e=>{dirty.current=true;setOffers(list=>list.map(o=>o.id===offer.id?{...o,pages:e.target.value.split(',').map(Number).filter(n=>Number.isInteger(n)&&n>0)}:o));}}/></label></fieldset>)}
    <button disabled={disabled||!original} onClick={()=>action('comparison',{offers,selectedId,note})}>保存比较版本／重新核对决定</button><small>版本 {flow?.comparisonVersion??0} · 修改方案后须重新取得客户决定。</small>
   </section>
   <div className={styles.snapshots}><div>{files.length>1&&<select aria-label="目前原件" value={shownFile?.id??''} onChange={e=>setCurrentFile(e.target.value)}>{files.map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select>}{shownFile?<Snapshot src={pdfUrl('fileId',shownFile.id)} title="目前保单快照"/>:<section className={styles.snapshot}><h3>目前保单快照</h3><p>尚未关联正式原件。请先关联已有文件或补传一次。</p></section>}</div><div>{quoteCleaned&&newFile?<Snapshot src={pdfUrl('fileId',newFile.id)} title="已归档新保单快照"/>:selected&&!quoteCleaned?<Snapshot src={pdfUrl('jobId',selected.jobId)} title="选中方案快照" pages={selected.pages}/>:<section className={styles.snapshot}><h3>选中方案快照</h3><p>上传报价并选择方案后显示。</p></section>}</div></div>
   <section className={styles.card}><h2>客户决定与办理</h2><label>沟通日期、渠道／办理及文件核对依据<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="记录客户决定或保险公司确认依据"/></label><div className={styles.row}><button disabled={disabled||!note.trim()||dirty.current} onClick={()=>action('decision',{decision:'stay',note})}>客户选择续约</button><button disabled={disabled||!note.trim()||dirty.current} onClick={()=>action('decision',{decision:'switch',note})}>客户选择换公司</button><button disabled={disabled||!note.trim()} onClick={()=>action('decision',{decision:'cancel',note})}>客户要求取消</button></div><p>当前决定：{flow?.decision==='stay'?'留原公司续约':flow?.decision==='switch'?'换保险公司':flow?.decision==='cancel'?'取消现有保单':'尚未决定'}</p>
    <ol className={styles.steps}>{flow&&visibleSteps(flow).map(s=><li key={s.key}><span>{s.state==='done'?'✓':s.state==='skipped'?'—':'○'} {s.label}{s.key==='sign'?'（上传签署原件后核实）':''}</span>{!s.gate&&!['decision','archive','sign'].includes(s.key)&&<button disabled={disabled||!note.trim()} onClick={()=>manual(s.key)}>记录完成</button>}</li>)}</ol>
    {flow?.decision!=='cancel'&&flow?.decision!=='undecided'&&<fieldset disabled={disabled}><legend>保险公司确认的新年度／新保单</legend><label>实际税前保费 CAD<input type="number" min="0" step="0.01" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>正式保单号<input value={policyNumber} onChange={e=>setPolicyNumber(e.target.value)}/></label>{flow?.decision==='switch'&&<label><input type="checkbox" checked={pendingIssue} onChange={e=>setPendingIssue(e.target.checked)}/>已确认承保，正式编号待签发</label>}<label><input type="checkbox" checked={carrierConfirmed} onChange={e=>setCarrierConfirmed(e.target.checked)}/>已经得到保险公司确认，已核对投保人、标的与快照</label><div className={styles.row}>{!target?<button disabled={!carrierConfirmed||!price||!note.trim()} onClick={()=>action('create',{premiumCents:Math.round(Number(price)*100),policyNumber,pendingIssue,carrierConfirmed,note})}>建立续保年度／新保单</button>:<><p>{target.policy_number??target.binder_number} · {target.effectiveDate} — {target.expiryDate} · {target.status}</p>{target.binder_number&&<button disabled={!policyNumber} onClick={()=>action('issue',{policyNumber})}>记录正式保单号</button>}<button disabled={!carrierConfirmed||!price||!note.trim()} onClick={()=>action('actual',{premiumCents:Math.round(Number(price)*100),carrierConfirmed,note})}>确认实际生效与替换关系</button></>}</div></fieldset>}
    {['switch','cancel'].includes(flow?.decision??'')&&<fieldset disabled={disabled}><legend>旧保单取消确认</legend><label>保险公司确认的取消日期<input type="date" value={effectiveDate} onChange={e=>setEffectiveDate(e.target.value)}/></label><label><input type="checkbox" checked={cancelConfirmed} onChange={e=>setCancelConfirmed(e.target.checked)}/>已收到保险公司的取消确认</label><button disabled={!cancelConfirmed||!effectiveDate||!note.trim()} onClick={()=>action('cancel',{effectiveDate,carrierConfirmed:cancelConfirmed,note})}>保存实际取消事件</button><div className={styles.row}><label>账务结果<select value={billKind} onChange={e=>setBillKind(e.target.value as 'refund'|'charge')}><option value="refund">退款</option><option value="charge">补收／费用</option></select></label><label>确认金额 CAD<input type="number" min="0" step="0.01" value={billingPrice} onChange={e=>setBillingPrice(e.target.value)}/></label><label><input type="checkbox" checked={billingConfirmed} onChange={e=>setBillingConfirmed(e.target.checked)}/>已核实实际退款／费用</label><button disabled={!billingPrice||!note.trim()||!billingConfirmed} onClick={()=>action('billing',{kind:billKind,cents:Math.round(Number(billingPrice)*100),note,carrierConfirmed:billingConfirmed})}>保存账务结果</button></div><details><summary>金额待确认，建立账务跟进任务</summary><label>截止日期<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label><label>负责人<select value={ownerId} onChange={e=>setOwnerId(e.target.value)}><option value="">选择</option>{(navigation as any)?.members?.filter((m:any)=>m.active).map((m:any)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><button disabled={!dueDate||!ownerId||!note.trim()} onClick={()=>action('followup',{dueDate,ownerId,note})}>建立关联跟进任务</button></details></fieldset>}
   </section>
   {original&&<section className={styles.card}><h2>正式文件归档</h2><div className={styles.row}><label>归属年度<select value={fileTerm} onChange={e=>setFileTerm(e.target.value)}><option value="original">本次原年度</option>{target&&<option value="target">新保单／下一年度</option>}</select></label><label>文件类别<select value={documentKind} onChange={e=>setDocumentKind(e.target.value)}><option value="policy_original">正式保单原件</option><option value="renewal_original">续保原件</option><option value="endorsement">批单原件</option><option value="signed_application">签署投保文件</option><option value="cancellation_confirmation">取消确认</option></select></label><label className={styles.upload}>上传并归档<input aria-label="上传正式文件 PDF" type="file" accept="application/pdf" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(file,true);}}/></label></div><p>上传后自动归档到 ClientCoreBMS；quote 不会被自动改成正式原件。</p><div className={styles.row}><button disabled={disabled} onClick={()=>action('verify')}>核实生效与文件完整性</button><button disabled={disabled} onClick={()=>action('cleanup')}>正式文件到齐后删除临时报价</button><button disabled={disabled} onClick={()=>action('finish')}>完成任务</button></div>{r.cleanupPending&&<p>报价清理待重试。</p>}</section>}
  </>}
 </main></WorkspaceShell>;
}
