'use client';
import {useEffect,useRef,useState} from 'react';
import WorkspaceShell from './workspace-shell';
import {DensitySwitch} from './workspace-controls';
import type {NavigationData} from './workspace-navigation';
import type {FeedbackInput,RenewalFeedback} from '../lib/renewal-feedback';
import {clientGroups,decisionLabel,policyKey,portfolioTotal,shownPremium} from '../lib/renewal-csr-view';
import CsrSnapshot from './renewal-csr-snapshot';
import styles from './renewal-csr.module.css';

const money=(c:number|null)=>c==null?'Awaiting price':new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD'}).format(c/100);
const labels={current:'Current policies',renewal:'Renew with current insurer',alternative:'Alternative insurer'};
const slots=['current','renewal','alternative'] as const;
const time=(at:string)=>new Date(at).toLocaleString();

function Feedback({task,comparisonTaskId,policy,hash,history,members,onSaved}:{task:any;comparisonTaskId:string;policy:any;hash:string;history:RenewalFeedback[];members:any[];onSaved:()=>Promise<void>}) {
 const [note,setNote]=useState(''),[decision,setDecision]=useState<FeedbackInput['decision']>('undecided'),[channel,setChannel]=useState<FeedbackInput['channel']>('phone');
 const [reference,setReference]=useState<{hash:string;version:number}|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState('');
 const pending=useRef<FeedbackInput|null>(null),changed=reference&&(reference.hash!==hash||reference.version!==task.version);
 function edit(){if(!reference)setReference({hash,version:task.version});pending.current=null;setSaved('');}
 useEffect(()=>{if(!note.trim()&&!uncertain)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[note,uncertain]);
 useEffect(()=>{if(pending.current&&history.some(f=>f.requestId===pending.current!.requestId)){pending.current=null;setUncertain(false);setNote('');setReference(null);setSaved('Customer feedback saved.');}},[history]);
 async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');let definite=false;
  try{
   const input=pending.current??{requestId:crypto.randomUUID(),taskId:task.id,comparisonTaskId,version:reference?.version??task.version,comparisonHash:reference?.hash??hash,targetKind:policy.targetKind,targetId:policy.targetId,decision,channel,note:note.trim()};pending.current=input;
   const response=await fetch('/api/renewal-comparison',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}),body=await response.json();
   definite=response.status<500;if(!response.ok)throw Error(body.error??'Feedback could not be saved.');
   pending.current=null;setUncertain(false);setNote('');setReference(null);setSaved('Customer feedback saved.');await onSaved();
  }catch(e){setError(e instanceof Error?e.message:'Feedback could not be saved.');setUncertain(!definite);if(definite)pending.current=null;await onSaved().catch(()=>{});}finally{setBusy(false);}
 }
 const latest=history[0];
 return <section className={styles.feedback}><h4>Customer feedback{latest?` · ${decisionLabel[latest.decision]}`:''}</h4>{task.archived?<p>This task is archived. Saved feedback remains available below.</p>:<form onSubmit={save}>
  <label>Customer choice<select disabled={busy||uncertain} value={decision} onChange={e=>{edit();setDecision(e.target.value as FeedbackInput['decision']);}}>{Object.entries(decisionLabel).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
  <label>Communication channel<select disabled={busy||uncertain} value={channel} onChange={e=>{edit();setChannel(e.target.value as FeedbackInput['channel']);}}><option value="phone">Phone</option><option value="email">Email</option><option value="message">Message</option><option value="in_person">In person</option></select></label>
  <label className={styles.note}>Feedback / follow-up notes<textarea aria-label={'Feedback for '+policy.policyNumber} disabled={busy||uncertain} maxLength={4000} value={note} onChange={e=>{edit();setNote(e.target.value);}} placeholder="Customer questions, preference, decision, or next contact…"/></label>
  {changed&&!uncertain&&<div className={styles.notice}>The comparison or task changed while you were writing. Review the latest information, then <button type="button" onClick={()=>{setReference({hash,version:task.version});setError('');}}>Use latest reviewed version</button></div>}
  {error&&<div className={styles.error} role="alert">{error}</div>}
  <div className={styles.feedbackFooter}><span>Saved to Kanban with your name, time, and broker comparison version.</span><button className={styles.save} disabled={busy||!note.trim()||!!changed&&!uncertain}>{busy?'Saving…':uncertain?'Retry original feedback':'Save customer feedback'}</button></div>
 </form>}{saved&&<p className={styles.success} role="status">{saved}</p>}{history.length>0&&<details className={styles.history}><summary>Feedback history · {history.length}{history.some(f=>f.comparisonHash!==hash)?' · Earlier comparison versions included':''}</summary>{history.map(f=><article key={f.requestId}><strong>{decisionLabel[f.decision]}</strong><p>{f.note}</p><small>{members.find(m=>m.id===f.memberId)?.name??'Team member'} · {time(f.at)} · {f.channel} · Broker version {f.brokerRevision}</small></article>)}</details>}</section>;
}

function PolicyComparison({policy,task,comparisonTaskId,portfolio,frequency,feedback,members,onSaved}:{policy:any;task:any;comparisonTaskId:string;portfolio:any;frequency:'annual'|'monthly';feedback:RenewalFeedback[];members:any[];onSaved:()=>Promise<void>}) {
 const [slot,setSlot]=useState<'renewal'|'alternative'>(policy.broker.recommendation==='stay'?'renewal':policy.broker.alternative?'alternative':'renewal');
 const broker=policy.broker,current=broker.snapshots.current,proposed=broker.snapshots[slot];
 const url=(snapshot:any)=>'/api/renewal-comparison?taskId='+encodeURIComponent(task.id)+'&'+(snapshot.kind==='quote'?'jobId':'fileId')+'='+encodeURIComponent(snapshot.id);
 return <article className={styles.policy}><div className={styles.policyHeading}><div><h3>{policy.insurer} · {policy.policyNumber||'Policy number pending'}</h3><p>{policy.line}{policy.isCurrent===false?' · Renewal task period':''} · {policy.effectiveDate} — {policy.expiryDate}</p></div><small>Broker comparison {broker.revision||'pending'}{broker.reviewedAt?' · '+time(broker.reviewedAt):''}</small></div>
  <div className={styles.priceRow}>{slots.map(key=><article key={key}><small>{labels[key]}</small><strong>{money(shownPremium(policy,key,frequency))}</strong><p>{key==='current'?policy.insurer:broker[key]?.insurer??'Awaiting broker quote'}</p>{key==='current'&&<small>{policy.premiumBasis==='annual'?'Annual premium':policy.premiumBasis==='remaining_term'?'Remaining term premium':'Term premium'}</small>}{key!=='current'&&<><small>{broker[key]?.effectiveDate??'—'} — {broker[key]?.expiryDate??'—'}</small><button type="button" aria-pressed={slot===key} onClick={()=>setSlot(key)}>View snapshot</button></>}</article>)}</div>
  {broker.comparison?.length>0&&<div className={styles.tableScroll}><table className={styles.table}><caption>Reviewed coverage comparison</caption><thead><tr><th>Coverage</th><th>Current</th><th>Renewal</th><th>Alternative</th></tr></thead><tbody>{broker.comparison.map((row:any,i:number)=><tr key={i}><th scope="row">{row.label}</th><td>{row.current||'Unconfirmed'}</td><td>{row.renewal||'Unconfirmed'}</td><td>{row.alternative||'Unconfirmed'}</td></tr>)}</tbody></table></div>}{broker.reason&&<p className={styles.recommendation}><strong>Broker recommendation · {decisionLabel[broker.recommendation as keyof typeof decisionLabel]}</strong><br/>{broker.reason}</p>}
  {proposed?.kind==='quote'&&!proposed.priceMatched&&<p className={styles.estimate}>Uploaded quote snapshot · price linkage is awaiting broker review.</p>}
  <div className={styles.snapshots}>{current?<CsrSnapshot src={url(current)} title="Current policy snapshot" pages={current.pages}/>:<section className={styles.snapshot}><header><strong>Current policy snapshot</strong></header><p>No PDF snapshot is available through the connected ClientCore API.</p></section>}{proposed?<CsrSnapshot src={url(proposed)} title={slot==='renewal'?'Renewal snapshot':'Alternative snapshot'} pages={proposed.pages}/>:<section className={styles.snapshot}><header><strong>{slot==='renewal'?'Renewal snapshot':'Alternative snapshot'}</strong></header><p>No PDF snapshot is available through the connected ClientCore API. Manually entered prices remain visible above.</p></section>}</div>
  <Feedback key={policyKey(policy)} task={task} comparisonTaskId={comparisonTaskId} policy={policy} hash={portfolio.comparisonHash} history={feedback.filter(f=>f.targetKind===policy.targetKind&&f.targetId===policy.targetId||f.targetKind==='source'&&f.targetId===policy.sourceTargetId)} members={members} onSaved={onSaved}/>
 </article>;
}

export default function RenewalCsr({taskId}:{taskId?:string}) {
 const [navigation,setNavigation]=useState<NavigationData|null>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[frequency,setFrequency]=useState<'annual'|'monthly'>('annual'),[compact,setCompact]=useState(true),[busy,setBusy]=useState(false);
 const request=useRef(0);
 async function load(){const sequence=++request.current,response=await fetch('/api/renewal-comparison'+(taskId?'?taskId='+encodeURIComponent(taskId):''),{cache:'no-store'}),next=await response.json();if(!response.ok)throw Error(next.error??'Comparison could not be loaded.');if(sequence===request.current)setData(next);}
 useEffect(()=>{setData(null);void fetch('/api/state',{cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw Error(body.error);setNavigation(body);}).catch(e=>setError(String(e)));void load().catch(e=>setError(String(e)));return()=>{request.current++;};},[taskId]);
 useEffect(()=>{if(!taskId)return;const timer=setInterval(()=>{void load().catch(()=>{});},15000);return()=>clearInterval(timer);},[taskId]);
 async function refresh(){setBusy(true);setError('');try{await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function start(policy:any){setBusy(true);setError('');try{const res=await fetch('/api/renewals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'start',data:{kind:policy.targetKind,targetId:policy.targetId,clientId:policy.clientId}})}),body=await res.json();if(!res.ok)throw Error(body.error);window.location.href='/renewals?taskId='+encodeURIComponent(body.taskId);}catch(e){setError(String(e));setBusy(false);}}
 async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op:'logout'})});window.location.href='/';}
 const portfolio=data?.portfolio,policies=portfolio?.policies??[],currentPolicies=policies.filter((p:any)=>p.isCurrent!==false),client=portfolio?.client,groups=clientGroups(data?.items??[]).filter(g=>(g.code+' '+g.name+' '+g.policies.map(p=>p.policyNumber).join(' ')).toLowerCase().includes(search.toLowerCase()));
 return <WorkspaceShell page="renewals" data={navigation} onLogout={logout} className={styles.page}><main>
  <header className={styles.heading}><div><small>CSR WORKSPACE</small><h1>Renewal comparison</h1>{!compact&&<p>Client policies, broker quotes, original snapshots, and customer feedback.</p>}</div><div className={styles.row}><button onClick={()=>void refresh()} disabled={busy}>Refresh</button>{taskId&&<><DensitySwitch checked={compact} onChange={setCompact} label="Compact mode"/><a href="/renewals">All clients</a>{navigation?.me.role==='admin'&&<a href={'/renewals?taskId='+encodeURIComponent(taskId)+'&mode=operations'}>Policy processing</a>}</>}</div></header>
  {error&&<p className={styles.error} role="alert">{error}</p>}{!data&&<p className={styles.empty}>{error?'Customer information could not be loaded. Use Refresh to retry.':'Loading customer information…'}</p>}
  {!taskId&&data&&<><div className={styles.toolbar}><input aria-label="Find renewal client" placeholder="Find client, code, or policy number" value={search} onChange={e=>setSearch(e.target.value)}/><small>{groups.length} clients · {groups.reduce((count,group)=>count+group.policies.length,0)} upcoming policies</small></div>
   <div className={styles.queue}><table className={styles.clientList}><caption className={styles.srOnly}>Clients with upcoming renewals</caption><thead><tr><th scope="col">Client</th><th scope="col">Insurer</th><th scope="col">Policies due</th><th scope="col">Next expiry</th><th scope="col"><span className={styles.srOnly}>Action</span></th></tr></thead><tbody>{groups.map(group=>{const linked=group.policies.find(p=>p.taskId);return <tr key={group.clientId}><th scope="row"><strong>{group.name}</strong><small>{group.code}</small></th><td data-label="Insurer" className={styles.insurers}>{group.policies.map(p=>p.insurer).filter((v,i,list)=>list.indexOf(v)===i).join(' · ')}</td><td data-label="Policies due" className={styles.policyCount}>{group.policies.length}</td><td data-label="Next expiry" className={styles.expiry}><time dateTime={group.policies[0].expiryDate}>{group.policies[0].expiryDate}</time></td><td className={styles.listAction}>{linked?<a aria-label={'Compare policies for '+group.name} href={'/renewals?taskId='+encodeURIComponent(linked.taskId)}>Compare <span aria-hidden="true">→</span></a>:navigation?.me.role==='admin'?<button disabled={busy} onClick={()=>void start(group.policies[0])}>Create task</button>:<small>Awaiting broker task</small>}</td></tr>;})}</tbody></table>{!groups.length&&<p className={styles.empty}>No clients match this search.</p>}</div></>}
  {portfolio&&<><section className={styles.client}><div className={styles.clientHeader}><div><small>{client.code}</small><h2>{client.name}</h2><p>{currentPolicies.length} current policies · Information as of {portfolio.asOf}</p></div><div role="group" aria-label="Payment display"><button aria-pressed={frequency==='annual'} onClick={()=>setFrequency('annual')}>Annual / term</button><button aria-pressed={frequency==='monthly'} onClick={()=>setFrequency('monthly')}>Monthly</button></div></div><div className={styles.contacts}>{client.contacts?.map((c:any,i:number)=><span key={i}>{c.type||c.kind} {c.value}</span>)}</div></section>
   <div className={styles.totals}>{slots.map(slot=>{const total=portfolioTotal(policies,slot,frequency);return <article key={slot}><small>{labels[slot]} · {frequency==='annual'?'Total premium':'Monthly estimate'}</small><strong>{total.known?money(total.cents):'Awaiting prices'}</strong><small>{total.missing?`${total.known} / ${currentPolicies.length} priced · Known subtotal`:`${currentPolicies.length} policies`}</small></article>;})}</div>
   {frequency==='monthly'&&<p className={styles.estimate}>12-installment estimate, zero down payment. Auto: 1.3% annual fee. Home: 8% tax + 3% annual fee. Nonannual or unconfirmed terms require a broker payment schedule.</p>}
   <details className={styles.clientFacts} open={!compact}><summary>Client information & all policies</summary><p>People: {client.people?.map((p:any)=>p.name).join(' · ')||'Not recorded'}</p><p>Addresses: {client.addresses?.map((a:any)=>[a.line1,a.line2,a.city,a.province,a.postalCode].filter(Boolean).join(', ')).join('; ')||'Not recorded'}</p>{client.notes&&<p>{client.notes}</p>}<div className={styles.tableScroll}><table className={styles.table}><thead><tr><th>Policy</th><th>Insurer / type</th><th>Term</th><th>Current</th><th>Renewal</th><th>Alternative</th></tr></thead><tbody>{policies.map((p:any)=><tr key={policyKey(p)}><td>{p.policyNumber||'Pending'}</td><td>{p.insurer} · {p.line}</td><td>{p.effectiveDate} — {p.expiryDate}</td>{slots.map(s=><td key={s}>{money(shownPremium(p,s,frequency))}</td>)}</tr>)}</tbody></table></div></details>
   {portfolio.groups.map((group:any)=><details className={styles.asset} key={group.id} open={group.policyKeys.some((key:string)=>data.policyTasks?.[key]?.id===data.task.id)}><summary><strong>{group.name}</strong><small>{group.kind==='unlinked'?'Asset link not recorded':group.kind} · {group.policyKeys.length} {group.policyKeys.length===1?'policy':'policies'}</small></summary><div className={styles.assetBody}>{group.asset?.details&&<p className={styles.assetFacts}>{[group.asset.details.vin,group.asset.details.year,group.asset.details.type,group.asset.details.use].filter(v=>v&&v!=='unknown').join(' · ')}</p>}{group.policyKeys.map((key:string)=>{const p=policies.find((p:any)=>policyKey(p)===key);return p&&<PolicyComparison key={key} policy={p} task={data.policyTasks?.[key]??data.task} comparisonTaskId={data.task.id} portfolio={portfolio} frequency={frequency} feedback={data.feedback??[]} members={(navigation as any)?.members??[]} onSaved={load}/>;})}{!group.policyKeys.length&&<p className={styles.empty}>No current policy is linked to this asset.</p>}</div></details>)}
  </>}
 </main></WorkspaceShell>;
}
