'use client';
import {useState} from 'react';
import type {CustomerRef,Source,DraftTask} from '../lib/model';
import {quoteFields,generalFields} from '../lib/creation-fields';
import type {CreationForm} from '../lib/creation-form';
import {defaultChecklist,taskTypeLabels} from '../lib/task-templates';
import TaskSourceInbox from './task-source-inbox';
import styles from './task-creation.module.css';

async function api(path:string,body?:unknown){const r=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error||'请求失败');return result;}
export function SavedCreationForm({form}:{form:CreationForm}){const fields=form.kind==='new_customer_quote'?quoteFields:generalFields;return <details open className={styles.saved}><summary>{form.kind==='new_customer_quote'?'新客报价申请表':'任务创建表单'}</summary><p className={styles.hint}>已人工核对 · {new Date(form.reviewedAt).toLocaleString('zh-CN')}{form.quoteType&&' · '+{auto:'车险',home:'房屋险',both:'车房组合'}[form.quoteType]}</p><dl>{fields.filter(f=>form.values[f.key]).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.options?.[form.values[f.key]]??form.values[f.key]}</dd>{form.evidence[f.key]&&<p className={styles.evidence}>原文依据：{form.evidence[f.key]}</p>}</div>)}</dl></details>;}

export default function TaskCreationForm({sources,members,aiConfigured,onCreated}:{sources:Source[];members:{id:string;name:string;active:boolean}[];aiConfigured:boolean;onCreated:(id:string)=>Promise<void>}){
 const [kind,setKind]=useState<'new_customer_quote'|'existing_customer_task'>('new_customer_quote'),[type,setType]=useState<DraftTask['type']>('other'),[quoteType,setQuoteType]=useState<'auto'|'home'|'both'>('auto');
 const [q,setQ]=useState(''),[candidates,setCandidates]=useState<any[]>([]),[customer,setCustomer]=useState<CustomerRef|null>(null);
 const [values,setValues]=useState<Record<string,string>>({}),[evidence,setEvidence]=useState<Record<string,string>>({}),[sourceIds,setSourceIds]=useState<string[]>([]),[method,setMethod]=useState('manual');
 const [inboxBusy,setInboxBusy]=useState(false);
 const [ownerId,setOwnerId]=useState(''),[priority,setPriority]=useState<DraftTask['priority']>('normal'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'请求失败');}finally{setBusy(false);}}
 function reset(){setCustomer(null);setCandidates([]);setValues({});setEvidence({});setSourceIds([]);setReviewed(false);setMethod('manual');setNotice('');setQ('');}
 function selectSources(ids:string[]){setSourceIds(ids);setEvidence({});setReviewed(false);}
 function edit(key:string,value:string){setValues(v=>({...v,[key]:value}));setEvidence(v=>{const next={...v};delete next[key];return next;});setReviewed(false);}
 async function identify(ids:string[]){await run(async()=>{const result=await api('/api/task-creation/extract',{kind,sourceIds:ids,...(kind==='existing_customer_task'?{clientId:customer!.clientCoreId}:{})});const next={...values},quotes={...evidence};for(const [key,value]of Object.entries(result.values))if(!next[key]){next[key]=String(value);if(result.evidence[key])quotes[key]=String(result.evidence[key]);}setValues(next);setEvidence(quotes);setMethod(result.model);setReviewed(false);setNotice(['识别结果只填空白项；请对照原始资料核对。',...result.warnings].join(' '));});}
 async function save(){await run(async()=>{
  const quote=kind==='new_customer_quote',name=quote?(values.full_name??'').trim():customer!.displayName;
  const task:DraftTask={title:quote?(title.trim()||`${{auto:'车险',home:'房屋险',both:'车房组合'}[quoteType]}报价 · ${name}`):values.title??'',type:quote?'lead':type,priority,insuranceLine:quote?(quoteType==='both'?'combined':quoteType):'other',customer:name,customerRef:quote?null:customer,description:quote?description:values.description??'',dueDate:quote?([quoteType!=='home'?values.auto_eff_date:'',quoteType!=='auto'?values.home_eff_date:''].filter(Boolean).sort()[0]||null):(values.dueDate||null),ownerId:ownerId||null,checklist:defaultChecklist(quote?'lead':type)};
  const result=await api('/api/state',{op:'createTask',task,sourceIds,creationForm:{kind,...(quote?{quoteType}:{}),values:quote?{...values,full_name:name}:{...values,title:task.title,description:task.description},evidence,extraction:method,reviewed:true}});await onCreated(result.taskId);
 });}
 const allowed=kind==='new_customer_quote'||!!customer,fields=kind==='new_customer_quote'?quoteFields:generalFields;
 return <div><p className={styles.hint}>{kind==='new_customer_quote'?'新客报价：选资料 → 识别并填写客户及报价信息 → 核对并创建任务':'已有客户：确认 ClientCoreBMS 客户 → 选资料并填表 → 核对并创建任务'}</p>{error&&<p role="alert" className={styles.error}>{error}</p>}
 <fieldset className={styles.controls} disabled={busy||inboxBusy}>  <label>任务种类<select aria-label="任务种类" value={kind} onChange={e=>{setKind(e.target.value as typeof kind);reset();}}><option value="new_customer_quote">新客报价（暂无 BMS 客户档案）</option><option value="existing_customer_task">已有客户的一般任务</option></select></label></fieldset>
 <div className={styles.flow}><div className={styles.editor}><fieldset className={styles.controls} disabled={busy||inboxBusy}>

  {kind==='new_customer_quote'?<><p className={styles.confirmed}>新客户不需要查找 BMS。请从右侧资料识别姓名和联系方式；创建任务时保留为待建档客户。</p><label>报价险种<select aria-label="报价险种" value={quoteType} onChange={e=>{setQuoteType(e.target.value as typeof quoteType);setReviewed(false);}}><option value="auto">车险</option><option value="home">房屋险</option><option value="both">车房组合</option></select></label></>:<><label>一般任务类型<select aria-label="一般任务类型" value={type} onChange={e=>{setType(e.target.value as typeof type);setReviewed(false);}}>{(['other','renewal','documents'] as const).map(t=><option key={t} value={t}>{taskTypeLabels[t]}</option>)}</select></label><label>查找 ClientCoreBMS 客户<input placeholder="客户编号、姓名或保单号" value={q} onChange={e=>setQ(e.target.value)}/></label><button type="button" className="secondary" disabled={q.trim().length<2} onClick={()=>void run(async()=>{const result=await api('/api/customers?q='+encodeURIComponent(q.trim()));setCandidates(result.items);if(!result.items.length)setNotice('未找到客户，请核对编号或姓名');})}>查找</button>{candidates.map(c=><button type="button" className="secondary" key={c.id} onClick={()=>void run(async()=>{const result=await api('/api/customers?clientCoreId='+encodeURIComponent(c.id));setCustomer(result.customerRef);setCandidates([]);setValues({});setEvidence({});setSourceIds([]);setReviewed(false);setMethod('manual');setNotice('');})}>确认客户：{c.displayName} · {c.clientCode}</button>)}{customer&&<p className={styles.confirmed}><strong>已确认：{customer.displayName} · {customer.clientCode}</strong><br/>BMS ID：{customer.clientCoreId}</p>}</>}
  {allowed&&<><h3>{kind==='new_customer_quote'?'客户及报价资料':'任务信息'}</h3>{kind==='new_customer_quote'&&<p className={styles.hint}>姓名及电话或邮箱必填。其他资料可以留空，后续补齐；AI 不会自动创建 BMS 客户。</p>}<div className={kind==='new_customer_quote'?styles.quoteFields:styles.controls}>{fields.map(f=><label key={f.key}>{f.label}{f.required?' *':''}{f.kind==='select'?<select aria-label={f.label+(f.required?' *':'')} value={values[f.key]??''} onChange={e=>edit(f.key,e.target.value)}><option value="">待确认</option>{Object.entries(f.options!).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:f.kind==='long'?<textarea aria-label={f.label+(f.required?' *':'')} rows={4} value={values[f.key]??''} onChange={e=>edit(f.key,e.target.value)}/>:<input aria-label={f.label+(f.required?' *':'')} type={f.kind==='date'?'date':f.key==='email'?'email':'text'} value={values[f.key]??''} onChange={e=>edit(f.key,e.target.value)}/>} {evidence[f.key]&&<small className={styles.evidence}>原文依据：{evidence[f.key]}</small>}</label>)}</div>
  {kind==='new_customer_quote'&&<><label>任务标题（可选）<input value={title} placeholder="默认使用险种和客户姓名" onChange={e=>{setTitle(e.target.value);setReviewed(false);}}/></label><label>补充说明<textarea value={description} rows={3} onChange={e=>{setDescription(e.target.value);setReviewed(false);}}/></label></>}
  <div className={styles.actions}><label>负责人<select aria-label="负责人" value={ownerId} onChange={e=>{setOwnerId(e.target.value);setReviewed(false);}}><option value="">待分配</option>{members.filter(m=>m.active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>优先级<select aria-label="优先级" value={priority} onChange={e=>{setPriority(e.target.value as typeof priority);setReviewed(false);}}><option value="urgent">紧急</option><option value="high">高</option><option value="normal">普通</option><option value="low">低</option></select></label></div><label className={styles.check}><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>我已核对客户信息、表单内容与所选资料。</label><button type="button" className="primary full" disabled={!reviewed} onClick={()=>void save()}>{busy?'处理中…':'核对后创建任务'}</button></>}
 </fieldset>{notice&&<p role="status" className={styles.hint}>{notice}</p>}</div>{allowed?<TaskSourceInbox key={kind+customer?.clientCoreId} sources={sources} selected={sourceIds} onSelect={selectSources} onExtract={identify} busy={busy} aiConfigured={aiConfigured} onWorkingChange={setInboxBusy}/>:<p className={styles.confirmed}>确认客户后，右侧会显示资料收件箱。</p>}</div></div>;
}
