'use client';
import {useState,useEffect} from 'react';
import {cancellationTargetId} from '../lib/cancellation';
import type {Task} from '../lib/model';
export default function WorkflowBusiness({task,stepKey,onRefresh}:{task:Task;stepKey:string;onRefresh:()=>Promise<void>}) {
 const step=task.workflow?.steps.find(s=>s.key===stepKey),documents=step?.gate==='documents';
 const [targets,setTargets]=useState<any[]>([]),[sourcePolicies,setSourcePolicies]=useState<any[]>([]),[termId,setTermId]=useState(task.workflow?.pendingConfirmation?.termId??(stepKey==='cancellation'?task.workflow?.originalTermId:task.workflow?.targetTermId)??''),[originalTermId,setOriginalTermId]=useState(task.workflow?.originalTermId??''),[date,setDate]=useState(''),[premium,setPremium]=useState(''),[source,setSource]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[record,setRecord]=useState(false),[wholePolicyCancellation,setWholePolicyCancellation]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch('/api/workflow?taskId='+encodeURIComponent(task.id));const b=await r.json();if(!r.ok)throw Error(b.error);setTargets(b.items);setSourcePolicies(b.sourcePolicies??[]);if(step?.policyKey)setTermId(cancellationTargetId(step.policyKey,b.sourcePolicies??[])??'');setError('');}catch(e){setError(String(e));}finally{setBusy(false);}}
 useEffect(()=>{if(task.customerRef)void load();},[task.customerRef?.clientCoreId]);
 async function submit(mode:'verify'|'record'|'retry'){setBusy(true);setError('');try{const r=await fetch('/api/workflow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:task.id,version:task.version,stepKey,termId,originalTermId,mode,wholePolicyCancellation,effectiveDate:date,source,...(mode==='record'?{effectiveDate:date,source,...(stepKey==='actual'?{premiumCents:Math.round(Number(premium)*100)}:{})}:{})})});const b=await r.json();if(!r.ok)throw Error(b.error);await onRefresh();}catch(e){setError(String(e));await onRefresh();}finally{setBusy(false);}}
 const expectedTermId=step?.policyKey?cancellationTargetId(step.policyKey,sourcePolicies):null;
 const choices=step?.policyKey?targets.filter(t=>t.id===expectedTermId):targets;
 return <div>{step?.policyKey&&!busy&&!expectedTermId&&<p role="status">该导入保单尚未关联办理年度，请先在 ClientCoreBMS 核对并关联；不会自动建单。</p>}{task.changeForm&&stepKey==='change'&&<p>此任务含具体字段变更。请先在 ClientCoreBMS 记录实际变更，再核实已有记录；此处不会把申请内容自动写入档案。</p>}{task.type==='property_remove'&&stepKey==='change'&&<label><input type="checkbox" disabled={!!task.workflow?.pendingConfirmation} checked={wholePolicyCancellation} onChange={e=>setWholePolicyCancellation(e.target.checked)}/>此次房产移除需要整张保单取消</label>}<p>核实已有记录，或录入已经得到保险公司确认的事实。不会向保险公司发送申请。</p><button type="button" disabled={busy||!task.customerRef} onClick={load}>刷新保单</button>{task.type==='renewal'&&stepKey==='actual'&&<label>原保单年度<select value={originalTermId} onChange={e=>setOriginalTermId(e.target.value)}><option value="">选择原保单年度</option>{targets.map(t=><option key={t.id} value={t.id}>{t.policy_number} · {t.effective_date} — {t.expiry_date}</option>)}</select></label>}<select disabled={!!task.workflow?.pendingConfirmation} aria-label="关联保单年度" value={termId} onChange={e=>setTermId(e.target.value)}><option value="">选择对应保单年度</option>{choices.map(t=><option key={t.id} value={t.id}>{t.policy_number} · {t.insurer} · {t.effective_date} — {t.expiry_date}</option>)}</select><label>{documents?'文件完整性核对依据':'确认依据（文件及页码）'}<textarea value={source} onChange={e=>setSource(e.target.value)}/></label>{stepKey!=='actual'&&!documents&&<label>本次事件生效日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{task.workflow?.pendingConfirmation?<button type="button" disabled={busy} onClick={()=>submit('retry')}>核实／重试原提交</button>:<><button type="button" disabled={busy||!termId} onClick={()=>submit('verify')}>核实已有业务记录</button>{!documents&&!(task.changeForm&&stepKey==='change')&&<details open={record} onToggle={e=>setRecord(e.currentTarget.open)}><summary>录入已确认的业务事实</summary>{stepKey==='actual'&&<label>生效日期<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{stepKey==='actual'&&<label>税前实际保费 CAD<input type="number" min="0" step="0.01" value={premium} onChange={e=>setPremium(e.target.value)}/></label>}<button type="button" disabled={busy||!termId||!date||!source.trim()||(stepKey==='actual'&&!premium)} onClick={()=>submit('record')}>确认并保存业务事实</button></details>}</>}{error&&<p role="alert">{error}</p>}</div>;
}
