'use client';
import WorkflowBusiness from './workflow-business';
import { useState } from 'react';
import type { Task } from '../lib/model';
import { visibleSteps } from '../lib/task-workflow';
import styles from './workflow-panel.module.css';
export default function WorkflowPanel({task,onRefresh}:{task:Task;onRefresh:()=>Promise<void>}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[comparison,setComparison]=useState(task.workflow?.comparison??'');
 const flow=task.workflow;
 if(task.billingFollowup)return <section className={styles.panel}><h3>取消账务跟进</h3><a href={'/insurance-review?taskId='+encodeURIComponent(task.id)}>核对实际退款／费用并更新 BMS</a></section>;
 if(task.renewal)return <section className={styles.panel}><h3>续保办理进度</h3><a href={'/insurance-review?taskId='+encodeURIComponent(task.id)}>打开快照比价与完整办理页面</a><p>{flow?.decision==='cancel'?'取消保单':flow?.decision==='stay'?'留原公司续约':flow?.decision==='switch'?'换保险公司':'等待客户决定'}</p><ol>{flow&&visibleSteps(flow).map(s=><li key={s.key}>{s.state==='done'?'✓':'○'} {s.label}</li>)}</ol></section>;
 async function act(op:string,extra:Record<string,unknown>={}) {setBusy(true);setError('');try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,taskId:task.id,version:task.version,...extra})});const b=await r.json();if(!r.ok)throw new Error(b.error);await onRefresh();setSelected('');setNote('');}catch(e){setError(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
 return <section className={styles.panel}><h3>办理进度</h3><small>独立的车险和房屋保单请分别建立办理任务。</small>{error&&<p role="alert">{error}</p>}{!flow?<button type="button" disabled={busy} onClick={()=>act('workflow.start')}>添加默认办理节点</button>:<>
 {task.type==='renewal'&&<details><summary>报价 Review 与客户决定 · {flow.decision==='stay'?'留原公司':flow.decision==='switch'?'切换':'待决定'}</summary><label>方案、税前价格及保障差异<textarea value={comparison} onChange={e=>setComparison(e.target.value)}/></label><button type="button" disabled={busy||!comparison.trim()} onClick={()=>act('workflow.comparison',{text:comparison})}>保存比较版本</button><p>版本 {flow.comparisonVersion} · 修改方案后须重新确认客户决定。</p><label>沟通日期、渠道及客户确认依据<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><button type="button" disabled={busy||!note.trim()} onClick={()=>act('workflow.decision',{decision:'stay',note})}>客户选择留原公司</button><button type="button" disabled={busy||!note.trim()} onClick={()=>act('workflow.decision',{decision:'switch',note})}>客户同意切换</button></details>}
 <ol>{visibleSteps(flow).map(step=><li key={step.key}><button type="button" className={styles.step} onClick={()=>{setSelected(selected===step.key?'':step.key);setNote(step.note);}}><span>{step.state==='done'?'✓':step.state==='skipped'?'—':'○'}</span>{step.label}<small>{step.state==='done'?'已完成':step.state==='skipped'?'不适用':''}</small></button>{selected===step.key&&<div className={styles.editor}>{step.gate?<><WorkflowBusiness key={step.key} task={task} stepKey={step.key} onRefresh={onRefresh}/>{task.type==='address'&&step.key==='change'&&<details><summary>仅通讯地址变化，无保障变更</summary><textarea aria-label="无保障变更依据" value={note} onChange={e=>setNote(e.target.value)}/><button type="button" disabled={busy||!note.trim()} onClick={()=>act('workflow.step',{key:step.key,state:'skipped',note})}>记录本次无需保单变更</button></details>}</>:step.key==='decision'?<p>请在上方记录客户对当前方案的决定。</p>:<><textarea aria-label="办理依据或不适用原因" value={note} onChange={e=>setNote(e.target.value)} placeholder="办理备注；不适用时必填原因"/><button type="button" disabled={busy} onClick={()=>act('workflow.step',{key:step.key,state:'done',note})}>完成</button><button type="button" disabled={busy||!note.trim()} onClick={()=>act('workflow.step',{key:step.key,state:'skipped',note})}>不适用</button><button type="button" disabled={busy} onClick={()=>act('workflow.step',{key:step.key,state:'pending',note})}>重新打开</button></>}{step.at&&<small>{new Date(step.at).toLocaleString('zh-CN')} · {step.note}</small>}</div>}</li>)}</ol></>}</section>;
}
